version: "3.9"
services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - "7070:80"
  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: edureka
  phpadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - wordpress_db:mysql
    ports:
      - "8181:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: edureka
